rules:
  indent: ["error", 2]
  no-cond-assign: "error"
  no-empty: "error"
  no-extra-semi: "error"
  no-irregular-whitespace: "error"
  no-unreachable: "error"
  curly: "error"
  no-eval: "error"
  no-floating-decimal: "error"
  no-native-reassign: "error"
  no-octal: "error"
  no-redeclare: "error"
  no-unused-vars: "error"
  block-spacing: "error"
  comma-style: ["error", "last"]
  consistent-this: ["error", "that"]
  eol-last: "error"
  no-spaced-func: "error"
  no-trailing-spaces: "error"

env:
  commonjs: true

parserOptions:
  sourceType: "module"
  ecmaVersion: 6
